version: "3.1"
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: my_custom_db
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker-compose/db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge